id: load_bike_data_gcp
namespace: project1

description: |
  Best to add a label `backfill:true` from the UI to track executions created via a backfill.
  CSV data used here comes from: https://divvy-tripdata.s3.amazonaws.com/202101-divvy-tripdata.zip

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [divvy]
    defaults: divvy

  - id: year
    type: SELECT
    displayName: Select year
    values: ["2021", "2022", "2023", "2024", "2025"]
    defaults: "2025"
    allowCustomValue: true

  - id: month
    type: SELECT
    displayName: Select month
    values: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
    defaults: "01"

variables:
  file: "{{inputs.year}}{{inputs.month}}-{{inputs.taxi}}-tripdata"
  file1: "{{inputs.year}}{{inputs.month}}"
  gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{vars.file}}"
  source_url: "https://divvy-tripdata.s3.amazonaws.com/{{vars.file}}.zip"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      taxi: "{{inputs.taxi}}"

  - id: debug_vars
    type: io.kestra.core.tasks.log.Log
    message: |
      File: {{render(vars.file)}}
      Source URL: {{render(vars.source_url)}}
      GCS Path: {{render(vars.gcs_file)}}

  - id: download_file
    type: io.kestra.plugin.core.http.Download
    uri: "{{render(vars.source_url)}}"

  - id: unzip
    type: io.kestra.plugin.compress.ArchiveDecompress
    algorithm: ZIP
    from: "{{outputs.download_file.uri}}"

  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{outputs.unzip.files[render(vars.file1) ~ '-divvy-tripdata.csv']}}"
    to: "gs://global-rookery-448215-m8_divvy_bikes/divvy-tripdata/{{inputs.year}}/{{vars.file1}}-divvy-tripdata.csv"

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  # Monthly schedule for new data
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"  # Runs at 9AM on the 1st of each month
    inputs:
      taxi: divvy
      year: "{{ now().year }}"
      month: "{{ now().month | format('02d') }}"